### ISSUE TITLE
Your Ruby version is 2.1.5, but your Gemfile specified 2.3.3

### ISSUE THREAD

**Issue by lfiocco** [jeffmcfadden/PiThermostat#3]
After bundle install I get 
Your Ruby version is 2.1.5, but your Gemfile specified 2.3.3

**Comment by jeffmcfadden** [comment]
You'll need to install ruby 2.3.3, or update your Gemfile to say 2.1.5. Sorry about that. I'll have to update the docs.

**Comment by lfiocco** [comment]
What command line fixes this?

Sent from my iPad

On Apr 7, 2017, at 4:50 PM, Jeff McFadden <notifications@github.com<mailto:notifications@github.com>> wrote:


You'll need to install ruby 2.3.3, or update your Gemfile to say 2.1.5. Sorry about that. I'll have to update the docs.
