### ISSUE TITLE
Do the instructions work now?

### ISSUE THREAD

**Issue by lfiocco** [jeffmcfadden/PiThermostat#5]
Is there a dumbed down version on this thermostat. I need a thermostat that can control a pool Heater using a relay and 18b20. I only need homekit support via homebridge. I don't need all the data base stuff and charts.

**Comment by jeffmcfadden** [comment]
Short answer: there is no "dumbed down version".

If writing rails code is outside your wheelhouse then this probably isn't the project for you. You could look at the thermostat model (https://github.com/jeffmcfadden/PiThermostat/blob/master/app/models/thermostat.rb#L28) to see how we get the temperature from a 18B20 sensor and how we turn the pins on/off on the relay board (https://github.com/jeffmcfadden/PiThermostat/blob/master/app/models/thermostat.rb#L182). 

The app makes use of the WiringPi GPIO library to handle the relay changes. http://wiringpi.com/the-gpio-utility/

Hope you find what you're looking for.

**Comment by lfiocco** [comment]
If I follow the instruction from your site, will it work now? Or does rails still need to be fixed?

Sent from my iPad

On May 19, 2017, at 1:15 PM, Jeff McFadden <notifications@github.com<mailto:notifications@github.com>> wrote:


Short answer: there is no "dumbed down version".

If writing rails code is outside your wheelhouse then this probably isn't the project for you. You could look at the thermostat model (https://github.com/jeffmcfadden/PiThermostat/blob/master/app/models/thermostat.rb#L28) to see how we get the temperature from a 18B20 sensor and how we turn the pins on/off on the relay board (https://github.com/jeffmcfadden/PiThermostat/blob/master/app/models/thermostat.rb#L182).

The app makes use of the WiringPi GPIO library to handle the relay changes. http://wiringpi.com/the-gpio-utility/

Hope you find what you're looking for.
